import { RepositoryInfo, TechnologyProfile } from '../domain';
import { PlannedDocument } from './documentation-plan';

export const GENERATED_FILE_MARKER = '<!-- Generated by AI Project Docs. Safe to update. -->';

export interface DocumentTemplateProjectMetadata {
  generatedAt: string;
  repositoryInfo: RepositoryInfo;
  technologyProfile: TechnologyProfile;
}

function formatList(items: string[]): string {
  return items.length > 0 ? items.join(', ') : 'None detected yet';
}

function buildKnownContextLines(
  repositoryInfo: RepositoryInfo,
  technologyProfile: TechnologyProfile,
): string[] {
  return [
    `- Project root: \`${repositoryInfo.rootPath}\``,
    `- Detected top-level files: ${repositoryInfo.detectedFiles.length}`,
    `- Languages: ${formatList(technologyProfile.languages)}`,
    `- Frameworks: ${formatList(technologyProfile.frameworks)}`,
    `- Package managers: ${formatList(technologyProfile.packageManagers)}`,
    `- Tooling: ${formatList(technologyProfile.tooling)}`,
    `- Detection confidence: ${technologyProfile.confidence}`,
  ];
}

function buildDependencyLines(document: PlannedDocument): string[] {
  if (!document.dependsOn || document.dependsOn.length === 0) {
    return ['- No explicit document dependencies are declared for this file yet.'];
  }

  return document.dependsOn.map(
    (dependencyPath) => `- Read \`${dependencyPath}\` before relying on this document for implementation decisions.`,
  );
}

export function renderDeterministicDocument(
  document: PlannedDocument,
  metadata: DocumentTemplateProjectMetadata,
): string {
  const knownContext = buildKnownContextLines(
    metadata.repositoryInfo,
    metadata.technologyProfile,
  ).join('\n');
  const dependencyGuidance = buildDependencyLines(document).join('\n');

  return `${GENERATED_FILE_MARKER}

# ${document.title}

## Purpose

${document.purpose}

## Project

- Name: ${metadata.repositoryInfo.name}
- Generated: ${metadata.generatedAt}
- Status: initial deterministic documentation
- Source: ${document.source}
- Priority: ${document.priority}

This file is intentionally deterministic. It captures currently known repository metadata and planning context only. Deeper AI-assisted analysis will enrich this document in future pipeline steps.

## How AI agents should use this document

- Start here when your task matches this document's purpose.
${dependencyGuidance}
- Treat this file as a safe baseline, not as a complete architecture analysis.
- Cross-check implementation details in source files when the task depends on code-level behavior.

## Current known context

${knownContext}

## Next documentation improvements

- Add deeper repository structure analysis once the repository tree scanner is implemented.
- Add architecture findings after the AI analysis stage is introduced.
- Expand file-specific guidance with richer project context while preserving safe incremental updates.
`;
}
