import { ProjectKnowledge } from '../knowledge';
import { PlannedDocument } from '../domain/documentation-plan';

export const GENERATED_FILE_MARKER = '<!-- Generated by AI Project Docs. Safe to update. -->';

function formatList(items: string[]): string {
  return items.length > 0 ? items.join(', ') : 'None detected yet';
}

function buildKnownContextLines(knowledge: ProjectKnowledge): string[] {
  return [
    `- Project root: \`${knowledge.repository.rootPath}\``,
    `- Detected top-level files: ${knowledge.repository.detectedFiles.length}`,
    `- Languages: ${formatList(knowledge.technologies.languages)}`,
    `- Frameworks: ${formatList(knowledge.technologies.frameworks)}`,
    `- Package managers: ${formatList(knowledge.technologies.packageManagers)}`,
    `- Tooling: ${formatList(knowledge.technologies.tooling)}`,
    `- Detection confidence: ${knowledge.technologies.confidence}`,
  ];
}

function buildDependencyLines(document: PlannedDocument): string[] {
  if (!document.dependsOn || document.dependsOn.length === 0) {
    return ['- No explicit document dependencies are declared for this file yet.'];
  }

  return document.dependsOn.map(
    (dependencyPath) => `- Read \`${dependencyPath}\` before relying on this document for implementation decisions.`,
  );
}

export function renderDeterministicDocument(
  document: PlannedDocument,
  knowledge: ProjectKnowledge,
): string {
  const knownContext = buildKnownContextLines(knowledge).join('\n');
  const dependencyGuidance = buildDependencyLines(document).join('\n');

  return `${GENERATED_FILE_MARKER}

# ${document.title}

## Purpose

${document.purpose}

## Project

- Name: ${knowledge.repository.name}
- Generated: ${knowledge.metadata.generatedAt}
- PKM schema: ${knowledge.metadata.schemaVersion}
- Analysis status: ${knowledge.analysis.status}
- Status: initial deterministic documentation
- Source: ${document.source}
- Priority: ${document.priority}

This file is intentionally deterministic. It captures currently known repository metadata and planning context only. Deeper AI-assisted analysis will enrich this document in future pipeline steps.

## How AI agents should use this document

- Start here when your task matches this document's purpose.
${dependencyGuidance}
- Treat this file as a safe baseline, not as a complete architecture analysis.
- Cross-check implementation details in source files when the task depends on code-level behavior.

## Current known context

${knownContext}

## Next documentation improvements

- Add deeper repository structure analysis once the repository tree scanner is implemented.
- Add architecture findings after the AI analysis stage is introduced.
- Expand file-specific guidance with richer project context while preserving safe incremental updates.
`;
}
