import { GENERATED_FILE_MARKER } from '../docs/document-template';
import {
  finishDocument,
  humanizeIdentifier,
  inlineCode,
  tableCell,
} from '../docs/markdown-renderers/render-helpers';
import {
  FolderClassification,
  ModuleKnowledge,
  ProjectKnowledge,
} from '../knowledge';
import {
  EXPORT_CONVENTION_LIMIT,
  plannedDocumentPaths,
  renderConventionSummarySection,
  renderDependencySummarySection,
  renderNavigationMapSection,
  renderProjectAnalysisStats,
  renderReadingOrderSection,
  renderSafetyRulesSection,
  renderSourceOfTruthSection,
  selectKeyModules,
  formatYamlScalar,
} from './agent-export-sections';
import { formatDocsRelativePath } from './exporter-paths';

const ARCHITECTURE_CONVENTION_CATEGORIES: ReadonlyArray<string> = [
  'architecture',
  'repository-structure',
];

const BOUNDARY_CLASSIFICATION_ORDER: ReadonlyArray<FolderClassification> = [
  'source',
  'test',
  'config',
  'documentation',
  'scripts',
  'tooling',
  'build-output',
  'dependency-cache',
  'asset',
  'unknown',
];

const MODULE_MAP_LIMIT = 24;

function renderCursorFrontmatter(knowledge: ProjectKnowledge): string[] {
  const description = formatYamlScalar(
    `Project context for ${knowledge.metadata.projectName} — generated by AI Project Docs from the PKM`,
  );
  return [
    '---',
    `description: ${description}`,
    'alwaysApply: true',
    '---',
  ];
}

function renderProjectSummarySection(knowledge: ProjectKnowledge, exportedAt: string): string[] {
  return [
    '',
    '# AI Project Docs — Cursor rule',
    '',
    GENERATED_FILE_MARKER,
    '',
    'Derived from the Project Knowledge Model (PKM). Do not treat this file as authoritative over the PKM snapshot.',
    '',
    '## Project summary',
    '',
    `- Project: ${knowledge.metadata.projectName}`,
    `- Exported: ${exportedAt}`,
    `- PKM assembled: ${knowledge.metadata.generatedAt}`,
    `- PKM schema: ${knowledge.metadata.schemaVersion}`,
    `- Analysis status: ${knowledge.analysis.status}`,
    ...renderProjectAnalysisStats(knowledge),
  ];
}

function renderArchitectureBoundariesSection(knowledge: ProjectKnowledge): string[] {
  const folderContexts = knowledge.analysis.folderContexts;
  const conventions = knowledge.analysis.conventions;
  const lines = ['', '## Architecture boundaries', ''];

  if (!folderContexts || folderContexts.length === 0) {
    lines.push('Folder boundaries are unknown until folder analysis has populated the PKM.');
  } else {
    lines.push(
      'Respect folder classifications and responsibilities. Do not move logic across boundaries without checking module and dependency impact.',
      '',
    );

    for (const classification of BOUNDARY_CLASSIFICATION_ORDER) {
      const folders = folderContexts.filter((folder) => folder.classification === classification);
      if (folders.length === 0) {
        continue;
      }

      lines.push(`### ${humanizeIdentifier(classification)}`);
      lines.push('');
      for (const folder of folders.slice(0, 6)) {
        lines.push(`- ${inlineCode(folder.relativePath)} — ${folder.responsibility}`);
      }
      if (folders.length > 6) {
        lines.push(`- …and ${folders.length - 6} more ${classification} folders`);
      }
      lines.push('');
    }
  }

  const architectural = (conventions ?? []).filter((convention) =>
    ARCHITECTURE_CONVENTION_CATEGORIES.includes(convention.category),
  );

  if (architectural.length > 0) {
    lines.push('### Architectural conventions');
    lines.push('');
    for (const convention of architectural) {
      lines.push(
        `- **${convention.name}** (${convention.confidence}) — ${convention.description}`,
      );
    }
  }

  return lines;
}

function renderModuleMapSection(
  modules: ModuleKnowledge[] | undefined,
  docsDir: string,
  plannedPaths: ReadonlySet<string>,
): string[] {
  const lines = ['', '## Module map', ''];

  if (!modules || modules.length === 0) {
    lines.push('No modules are known yet. Module analysis has not run for this snapshot.');
    return lines;
  }

  const keyModules = selectKeyModules(modules, MODULE_MAP_LIMIT);

  lines.push('| Module | Type | Responsibility | Confidence |');
  lines.push('|---|---|---|---|');
  for (const module of keyModules) {
    lines.push(
      `| ${inlineCode(module.relativePath)} | ${module.type} | ${tableCell(module.responsibility)} | ${module.confidence} |`,
    );
  }

  if (modules.length > keyModules.length) {
    const suffix = plannedPaths.has('architecture.md')
      ? inlineCode(formatDocsRelativePath(docsDir, 'architecture.md'))
      : 'the full PKM';
    lines.push('', `…and ${modules.length - keyModules.length} more modules — see ${suffix}.`);
  }

  return lines;
}

export function renderCursorRules(knowledge: ProjectKnowledge, exportedAt: string): string {
  const docsDir = knowledge.metadata.docsDir;
  const plannedPaths = plannedDocumentPaths(knowledge);
  const lines = [
    ...renderCursorFrontmatter(knowledge),
    ...renderProjectSummarySection(knowledge, exportedAt),
    ...renderReadingOrderSection(knowledge, { title: 'Mandatory reading order' }),
    ...renderArchitectureBoundariesSection(knowledge),
    ...renderModuleMapSection(knowledge.analysis.modules, docsDir, plannedPaths),
    ...renderConventionSummarySection(knowledge.analysis.conventions, docsDir, plannedPaths, {
      limit: EXPORT_CONVENTION_LIMIT,
    }),
    ...renderNavigationMapSection(knowledge),
    ...renderDependencySummarySection(knowledge.analysis.dependencyGraph, docsDir, plannedPaths),
    ...renderSafetyRulesSection(knowledge, {
      includeAgentExportPaths: true,
    }),
    ...renderSourceOfTruthSection(knowledge, {
      formatLabel: 'This Cursor rule',
      regenerateCommand: 'ai-project-docs --export-agents --target cursor',
    }),
  ];

  return finishDocument(lines);
}
