import { RepositoryNode } from '../domain';
import {
  FolderClassification,
  FolderKnowledge,
  ProjectKnowledge,
} from '../knowledge/project-knowledge';
import {
  IGNORED_FOLDER_NAMES,
  KNOWN_SOURCE_MODULE_RESPONSIBILITIES,
  getKnowledgeDirectoryRelativePath,
  isImportantFile,
  isKnownSourceModule,
  isSourceModulePath,
  normalizeFolderName,
  toPosixPath,
} from './folder-constants';
import { classifyFolder } from './folder-classifier';

export interface FolderAnalysisResult {
  folders: FolderKnowledge[];
  totalFolders: number;
  documentableFolders: number;
  ignoredFolders: number;
}

export function shouldIgnoreFolder(relativePath: string, docsDir: string): boolean {
  const posixPath = toPosixPath(relativePath);
  const normalizedDocsDir = toPosixPath(docsDir);
  const knowledgePath = getKnowledgeDirectoryRelativePath(docsDir);

  if (posixPath === knowledgePath) {
    return true;
  }

  if (posixPath === normalizedDocsDir || posixPath.startsWith(`${normalizedDocsDir}/`)) {
    return true;
  }

  const segments = posixPath.split('/').filter((segment) => segment.length > 0);
  const folderName = segments[segments.length - 1] ?? '';
  return IGNORED_FOLDER_NAMES.has(folderName);
}

function inferResponsibility(
  classification: FolderClassification,
  name: string,
  relativePath: string,
): string {
  const normalizedName = normalizeFolderName(name);
  const posixPath = toPosixPath(relativePath);
  const knownSourceResponsibility = KNOWN_SOURCE_MODULE_RESPONSIBILITIES[normalizedName];

  if (knownSourceResponsibility !== undefined && isKnownSourceModule(relativePath, name)) {
    return knownSourceResponsibility;
  }

  if (posixPath.length === 0) {
    return 'Project root containing top-level configuration, documentation, and source entry points.';
  }

  if (classification === 'source') {
    if (normalizedName === 'src' || posixPath === 'src') {
      return 'Contains the main source code of the project.';
    }

    if (normalizedName === 'config' || normalizedName === 'configs') {
      if (isSourceModulePath(relativePath)) {
        return 'Contains configuration-related application code.';
      }
      return 'Contains project configuration files.';
    }

    return `Contains ${name} application source code.`;
  }

  switch (classification) {
    case 'test':
      return 'Contains automated tests for the project.';
    case 'config':
      return 'Contains project configuration files.';
    case 'documentation':
      if (normalizedName === '.ai-docs') {
        return 'Contains AI-readable project context generated by this tool.';
      }
      return 'Contains human-readable project documentation.';
    case 'build-output':
      return 'Contains compiled or generated build artifacts.';
    case 'dependency-cache':
      return 'Contains third-party dependency packages.';
    case 'asset':
      return 'Contains static assets served by the application.';
    case 'scripts':
      return 'Contains automation and utility scripts.';
    case 'tooling':
      return 'Contains development tooling and helper utilities.';
    default:
      return `Contains project files related to ${name}.`;
  }
}

function collectImportantFiles(children: RepositoryNode[] | undefined): string[] {
  if (children === undefined) {
    return [];
  }

  return children
    .filter((child) => child.type === 'file' && isImportantFile(child.name))
    .map((child) => child.relativePath)
    .sort();
}

function collectChildFolders(children: RepositoryNode[] | undefined): string[] {
  if (children === undefined) {
    return [];
  }

  return children
    .filter((child) => child.type === 'directory')
    .map((child) => child.name)
    .sort();
}

function collectChildFileNames(children: RepositoryNode[] | undefined): string[] {
  if (children === undefined) {
    return [];
  }

  return children.filter((child) => child.type === 'file').map((child) => child.name);
}

function buildFolderKnowledge(
  node: RepositoryNode,
  depth: number,
): FolderKnowledge {
  const childFileNames = collectChildFileNames(node.children);
  const childFolderNames = collectChildFolders(node.children);
  const classificationResult = classifyFolder({
    name: node.name,
    relativePath: node.relativePath,
    childFileNames,
    childFolderNames,
  });
  const signals = [...classificationResult.signals];

  if (node.truncated === true) {
    signals.push('tree-truncated:true');
  }

  return {
    path: node.path,
    relativePath: node.relativePath,
    name: node.name,
    depth,
    classification: classificationResult.classification,
    responsibility: inferResponsibility(
      classificationResult.classification,
      node.name,
      node.relativePath,
    ),
    importantFiles: collectImportantFiles(node.children),
    childFolders: childFolderNames,
    signals,
    confidence: classificationResult.confidence,
  };
}

function analyzeDirectoryNode(
  node: RepositoryNode,
  docsDir: string,
  depth: number,
  allFolders: FolderKnowledge[],
  documentableFolders: FolderKnowledge[],
): void {
  const ignored = shouldIgnoreFolder(node.relativePath, docsDir);
  const folderKnowledge = buildFolderKnowledge(node, depth);
  allFolders.push(folderKnowledge);

  if (!ignored) {
    documentableFolders.push(folderKnowledge);
  }

  if (ignored || node.children === undefined) {
    return;
  }

  for (const child of node.children) {
    if (child.type === 'directory') {
      analyzeDirectoryNode(child, docsDir, depth + 1, allFolders, documentableFolders);
    }
  }
}

function analyzeProjectRoot(
  repositoryTree: RepositoryNode,
  allFolders: FolderKnowledge[],
  documentableFolders: FolderKnowledge[],
): void {
  const importantFiles = collectImportantFiles(repositoryTree.children);
  const childFolders = collectChildFolders(repositoryTree.children);

  if (importantFiles.length === 0 && childFolders.length === 0) {
    return;
  }

  const rootKnowledge: FolderKnowledge = {
    path: repositoryTree.path,
    relativePath: '',
    name: repositoryTree.name,
    depth: 0,
    classification: importantFiles.length > 0 ? 'config' : 'unknown',
    responsibility: inferResponsibility(
      importantFiles.length > 0 ? 'config' : 'unknown',
      repositoryTree.name,
      '',
    ),
    importantFiles,
    childFolders,
    signals: ['folder-name:root'],
    confidence: importantFiles.length > 0 ? 'high' : 'low',
  };

  allFolders.push(rootKnowledge);
  documentableFolders.push(rootKnowledge);
}

function sortFolders(folders: FolderKnowledge[]): FolderKnowledge[] {
  return [...folders].sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

export function analyzeFolderKnowledge(knowledge: ProjectKnowledge): FolderAnalysisResult {
  const repositoryTree = knowledge.repository.repositoryTree;

  if (repositoryTree === undefined || repositoryTree.type !== 'directory') {
    return {
      folders: [],
      totalFolders: 0,
      documentableFolders: 0,
      ignoredFolders: 0,
    };
  }

  const docsDir = knowledge.metadata.docsDir;
  const allFolders: FolderKnowledge[] = [];
  const documentableFolders: FolderKnowledge[] = [];

  analyzeProjectRoot(repositoryTree, allFolders, documentableFolders);

  if (repositoryTree.children !== undefined) {
    for (const child of repositoryTree.children) {
      if (child.type === 'directory') {
        analyzeDirectoryNode(child, docsDir, 1, allFolders, documentableFolders);
      }
    }
  }

  return {
    folders: sortFolders(documentableFolders),
    totalFolders: allFolders.length,
    documentableFolders: documentableFolders.length,
    ignoredFolders: allFolders.length - documentableFolders.length,
  };
}

export function enrichProjectKnowledgeWithFolderAnalysis(
  knowledge: ProjectKnowledge,
): { knowledge: ProjectKnowledge; result: FolderAnalysisResult } {
  const result = analyzeFolderKnowledge(knowledge);
  const hasRepositoryTree =
    knowledge.repository.repositoryTree !== undefined &&
    knowledge.repository.repositoryTree.type === 'directory';

  return {
    knowledge: {
      ...knowledge,
      analysis: {
        ...knowledge.analysis,
        status: hasRepositoryTree ? 'partial' : knowledge.analysis.status,
        folderContexts: hasRepositoryTree ? result.folders : undefined,
      },
    },
    result,
  };
}
