import { ModuleType } from '../knowledge/project-knowledge';
import { toPosixPath } from './folder-constants';

export const MONOREPO_MODULE_CONTAINERS: Readonly<Record<string, ModuleType>> = {
  apps: 'application',
  packages: 'package',
  libs: 'library',
  projects: 'application',
  modules: 'feature',
};

export const SOURCE_MODULE_CONTAINERS: Readonly<Record<string, ModuleType>> = {
  'src/app': 'application',
  'src/apps': 'application',
  'src/features': 'feature',
  'src/modules': 'feature',
};

export const DIRECT_SOURCE_MODULES: Readonly<Record<string, ModuleType>> = {
  'src/components': 'component-group',
  'src/services': 'service-group',
  'src/core': 'core',
  'src/config': 'configuration',
  'src/shared': 'library',
  'src/knowledge': 'core',
  'src/scanner': 'core',
  'src/detectors': 'core',
  'src/docs': 'core',
  'src/analyzers': 'core',
  'src/domain': 'core',
  'src/ai': 'core',
  'src/utils': 'tooling',
};

export const STATIC_DOCUMENTATION_MODULE_PATHS = new Set(['docs']);

export const KNOWN_MODULE_RESPONSIBILITIES: Readonly<Record<string, string>> = {
  'src/knowledge':
    'Represents and persists the Project Knowledge Model used as the source of truth.',
  'src/scanner': 'Builds the repository tree used by analyzers.',
  'src/detectors': 'Detects technologies and tooling from repository metadata.',
  'src/docs': 'Plans and writes documentation outputs derived from project knowledge.',
  'src/analyzers': 'Derives higher-level architectural knowledge from the PKM.',
  'src/core': 'Contains pipeline orchestration and core application coordination logic.',
  'src/domain': 'Defines pure domain types and the declarative analysis pipeline.',
  'src/config': 'Resolves runtime configuration from CLI flags and environment variables.',
  'src/ai': 'Integrates with AI providers for architecture analysis.',
  'src/utils': 'Provides shared utility functions with no domain knowledge.',
  docs: 'Contains human-readable project documentation.',
};

export function isDirectChildOfContainer(relativePath: string, containerPath: string): boolean {
  const posixPath = toPosixPath(relativePath);
  const prefix = `${toPosixPath(containerPath)}/`;
  if (!posixPath.startsWith(prefix)) {
    return false;
  }

  const remainder = posixPath.slice(prefix.length);
  return remainder.length > 0 && !remainder.includes('/');
}

export function isDocumentationModulePath(relativePath: string, docsDir: string): boolean {
  const posixPath = toPosixPath(relativePath);
  return (
    STATIC_DOCUMENTATION_MODULE_PATHS.has(posixPath) || posixPath === toPosixPath(docsDir)
  );
}

export function isMonorepoContainerChild(relativePath: string): boolean {
  const posixPath = toPosixPath(relativePath);
  return Object.keys(MONOREPO_MODULE_CONTAINERS).some((container) =>
    isDirectChildOfContainer(posixPath, container),
  );
}

export function isSourceContainerChild(relativePath: string): boolean {
  const posixPath = toPosixPath(relativePath);
  return Object.keys(SOURCE_MODULE_CONTAINERS).some((container) =>
    isDirectChildOfContainer(posixPath, container),
  );
}

export function resolveDocumentationModuleResponsibility(
  relativePath: string,
  docsDir: string,
): string {
  const posixPath = toPosixPath(relativePath);
  if (posixPath === toPosixPath(docsDir)) {
    return 'Contains AI-readable project context generated by this tool.';
  }
  return KNOWN_MODULE_RESPONSIBILITIES.docs;
}
