import { AiInsightsKnowledge, ProjectKnowledge } from '../../knowledge';
import { sanitizeAiInsightMetadata, sanitizeAiInsightText } from '../../utils/ai-text-sanitizer';
import { inlineCode } from './render-helpers';

const AI_INSIGHTS_DISCLAIMER =
  '> **AI-generated enrichment.** Deterministic PKM sections above remain the source of truth. Verify against code when behavior matters.';

function nonEmptyInsightItems(items: string[] | undefined): string[] {
  if (!items) {
    return [];
  }

  const sanitized: string[] = [];
  for (const item of items) {
    const text = sanitizeAiInsightText(item);
    if (text.length > 0) {
      sanitized.push(text);
    }
  }
  return sanitized;
}

export function hasRenderableAiInsights(insights: AiInsightsKnowledge | undefined): boolean {
  if (!insights) {
    return false;
  }

  if (insights.architectureSummary && sanitizeAiInsightText(insights.architectureSummary).length > 0) {
    return true;
  }

  return (
    nonEmptyInsightItems(insights.risks).length > 0 ||
    nonEmptyInsightItems(insights.recommendations).length > 0 ||
    nonEmptyInsightItems(insights.agentGuidance).length > 0
  );
}

function renderBulletList(items: string[]): string[] {
  return items.map((item) => {
    const normalized = item.replace(/^[-*+]\s+/, '');
    return `- ${normalized}`;
  });
}

export function renderAiInsightsSection(knowledge: ProjectKnowledge): string[] {
  const insights = knowledge.analysis.aiInsights;
  if (!insights || !hasRenderableAiInsights(insights)) {
    return [];
  }

  const architectureSummary = insights.architectureSummary
    ? sanitizeAiInsightText(insights.architectureSummary)
    : '';
  const risks = nonEmptyInsightItems(insights.risks);
  const recommendations = nonEmptyInsightItems(insights.recommendations);
  const agentGuidance = nonEmptyInsightItems(insights.agentGuidance);

  const lines = [
    '',
    '## AI Insights',
    '',
    AI_INSIGHTS_DISCLAIMER,
    '',
    `Generated by: ${inlineCode(sanitizeAiInsightMetadata(insights.model))}`,
    `Generated at: ${sanitizeAiInsightMetadata(insights.generatedAt)}`,
    '',
  ];

  if (architectureSummary.length > 0) {
    lines.push('### Architecture Summary', '', architectureSummary, '');
  }

  if (risks.length > 0) {
    lines.push('### Risks', '', ...renderBulletList(risks), '');
  }

  if (recommendations.length > 0) {
    lines.push('### Recommendations', '', ...renderBulletList(recommendations), '');
  }

  if (agentGuidance.length > 0) {
    lines.push('### Agent Guidance', '', ...renderBulletList(agentGuidance), '');
  }

  return lines;
}
