import {
  ArchitectureStageKnowledge,
  ProjectKnowledge,
} from '../../knowledge';
import { sanitizeAiInsightMetadata, sanitizeAiInsightText } from '../../utils/ai-text-sanitizer';
import { inlineCode } from './render-helpers';
import { hasRenderableAiInsights, renderAiInsightsSection } from './ai-insights-renderer';

const STAGED_ARCHITECTURE_DISCLAIMER =
  '> **Staged architecture enrichment.** Deterministic PKM sections above remain the source of truth. Verify against code when behavior matters.';

function hasRenderableStagedArchitecture(
  architecture: ArchitectureStageKnowledge | undefined,
): architecture is ArchitectureStageKnowledge {
  if (!architecture) {
    return false;
  }

  const summary = architecture.summary ? sanitizeAiInsightText(architecture.summary) : '';
  const content = architecture.content ? sanitizeAiInsightText(architecture.content) : '';
  return summary.length > 0 || content.length > 0;
}

export function renderStagedArchitectureSection(knowledge: ProjectKnowledge): string[] {
  const architecture = knowledge.analysis.stagedDocumentation?.architecture;
  if (!hasRenderableStagedArchitecture(architecture)) {
    return [];
  }

  const summary = architecture.summary ? sanitizeAiInsightText(architecture.summary) : '';
  const content = architecture.content ? sanitizeAiInsightText(architecture.content) : '';
  const lines = [
    '',
    '## Staged Architecture Context',
    '',
    STAGED_ARCHITECTURE_DISCLAIMER,
    '',
    `- Status: ${architecture.status}`,
  ];

  if (architecture.model !== undefined) {
    lines.push(`- Generated by: ${inlineCode(sanitizeAiInsightMetadata(architecture.model))}`);
  }
  if (architecture.generatedAt !== undefined) {
    lines.push(`- Generated at: ${sanitizeAiInsightMetadata(architecture.generatedAt)}`);
  }
  if (architecture.documentPaths.length > 0) {
    lines.push(
      `- Related documents: ${architecture.documentPaths.map((path) => inlineCode(path)).join(', ')}`,
    );
  }

  lines.push('');

  if (summary.length > 0 && summary !== content) {
    lines.push('### Summary', '', summary, '');
  }

  if (content.length > 0) {
    lines.push('### Architecture body', '', content, '');
  } else if (summary.length > 0) {
    lines.push(summary, '');
  }

  if (architecture.warnings.length > 0) {
    lines.push('### Warnings', '');
    for (const warning of architecture.warnings) {
      lines.push(`- ${sanitizeAiInsightText(warning)}`);
    }
    lines.push('');
  }

  return lines;
}

/**
 * Prefers PKM-backed staged architecture output when present; falls back to
 * legacy `analysis.aiInsights` so older snapshots still render enrichment.
 */
export function renderArchitectureEnrichmentSection(knowledge: ProjectKnowledge): string[] {
  const staged = renderStagedArchitectureSection(knowledge);
  if (staged.length > 0) {
    return staged;
  }

  if (hasRenderableAiInsights(knowledge.analysis.aiInsights)) {
    return renderAiInsightsSection(knowledge);
  }

  return [];
}
