/**
 * Release-level integration tests.
 *
 * These tests run the compiled CLI against deterministic fixture repositories
 * and verify the full end-to-end pipeline, output integrity, incremental
 * behavior, and source-code safety guarantees.
 *
 * Prerequisites: `npm run build` must have run before `npm test`.
 */
import assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { spawnSync } from 'node:child_process';
import { describe, it, before } from 'node:test';

const PROJECT_ROOT = path.resolve(__dirname, '..');
const CLI_PATH = path.join(PROJECT_ROOT, 'dist', 'cli.js');
const FIXTURES_DIR = path.join(PROJECT_ROOT, 'test', 'fixtures');

const FIXTURE_TS = path.join(FIXTURES_DIR, 'fixture-typescript');
const FIXTURE_MONO = path.join(FIXTURES_DIR, 'fixture-monorepo');
const FIXTURE_MINIMAL = path.join(FIXTURES_DIR, 'fixture-minimal');

const GENERATED_MARKER = '<!-- Generated by AI Project Docs. Safe to update. -->';

interface CliResult {
  status: number | null;
  stdout: string;
  stderr: string;
}

function runCli(args: string[], cwd?: string): CliResult {
  const result = spawnSync(process.execPath, [CLI_PATH, ...args], {
    cwd: cwd ?? PROJECT_ROOT,
    encoding: 'utf-8',
    env: { ...process.env, OPENROUTER_API_KEY: undefined },
  });

  if (result.error) {
    throw new Error(`Failed to spawn CLI: ${result.error.message}`);
  }

  return {
    status: result.status,
    stdout: typeof result.stdout === 'string' ? result.stdout : String(result.stdout ?? ''),
    stderr: typeof result.stderr === 'string' ? result.stderr : String(result.stderr ?? ''),
  };
}

function readJson(filePath: string): unknown {
  const raw = fs.readFileSync(filePath, 'utf-8');
  return JSON.parse(raw);
}

function removeDocsDir(fixturePath: string, docsDir = '.ai-docs'): void {
  const target = path.join(fixturePath, docsDir);
  if (fs.existsSync(target)) {
    fs.rmSync(target, { recursive: true, force: true });
  }
}

function collectSourceFiles(fixturePath: string): Map<string, string> {
  const files = new Map<string, string>();

  function walk(dir: string): void {
    for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
      const fullPath = path.join(dir, entry.name);
      const rel = path.relative(fixturePath, fullPath);

      if (rel.startsWith('.ai-docs') || rel.startsWith('node_modules') || rel.startsWith('.git')) {
        continue;
      }

      if (entry.isDirectory()) {
        walk(fullPath);
      } else {
        files.set(rel, fs.readFileSync(fullPath, 'utf-8'));
      }
    }
  }

  walk(fixturePath);
  return files;
}

describe('Release integration — Fixture A (TypeScript)', () => {
  const docsDir = path.join(FIXTURE_TS, '.ai-docs');
  const knowledgeDir = path.join(docsDir, 'knowledge');

  before(() => {
    removeDocsDir(FIXTURE_TS);
  });

  it('exits with code 0 on a clean first run', () => {
    const result = runCli([FIXTURE_TS]);
    assert.equal(result.status, 0, `CLI failed:\nSTDOUT:\n${result.stdout}\nSTDERR:\n${result.stderr}`);
  });

  it('creates the .ai-docs directory', () => {
    assert.ok(fs.existsSync(docsDir), '.ai-docs directory not created');
  });

  it('creates project-knowledge.json with required PKM sections', () => {
    const pkm = path.join(knowledgeDir, 'project-knowledge.json');
    assert.ok(fs.existsSync(pkm), 'project-knowledge.json missing');

    const knowledge = readJson(pkm) as Record<string, unknown>;
    assert.ok(knowledge['metadata'], 'PKM missing metadata');
    assert.ok(knowledge['repository'], 'PKM missing repository');
    assert.ok(knowledge['technologies'], 'PKM missing technologies');
    assert.ok(knowledge['documentation'], 'PKM missing documentation');
    assert.ok(knowledge['analysis'], 'PKM missing analysis');
  });

  it('creates split knowledge files', () => {
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'repository.json')), 'repository.json missing');
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'technologies.json')), 'technologies.json missing');
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'analysis.json')), 'analysis.json missing');
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'documentation.json')), 'documentation.json missing');
  });

  it('creates required Markdown files', () => {
    for (const name of ['architecture.md', 'agent-navigation.md', 'folder-structure.md']) {
      assert.ok(fs.existsSync(path.join(docsDir, name)), `${name} missing`);
    }
  });

  it('writes the generated-file protection marker in generated Markdown', () => {
    const arch = fs.readFileSync(path.join(docsDir, 'architecture.md'), 'utf-8');
    assert.ok(arch.startsWith(GENERATED_MARKER), 'architecture.md missing generated marker');
  });

  it('creates ai-readiness.json and ai-readiness.md', () => {
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'ai-readiness.json')), 'ai-readiness.json missing');
    assert.ok(fs.existsSync(path.join(docsDir, 'ai-readiness.md')), 'ai-readiness.md missing');
  });

  it('has a valid readiness score that matches between JSON and Markdown', () => {
    const json = readJson(path.join(knowledgeDir, 'ai-readiness.json')) as {
      aiReadiness: { overallScore: number; level: string };
    };
    const score = json.aiReadiness.overallScore;
    assert.ok(typeof score === 'number' && score >= 0 && score <= 100, `Score out of range: ${score}`);

    const md = fs.readFileSync(path.join(docsDir, 'ai-readiness.md'), 'utf-8');
    assert.ok(md.includes(String(score)), 'Readiness Markdown score does not match JSON');
  });

  it('has consistent readiness score between full PKM and split file', () => {
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: { aiReadiness?: { overallScore: number } };
    };
    const split = readJson(path.join(knowledgeDir, 'ai-readiness.json')) as {
      aiReadiness: { overallScore: number };
    };
    assert.equal(
      pkm.analysis.aiReadiness?.overallScore,
      split.aiReadiness.overallScore,
      'PKM and split ai-readiness score mismatch',
    );
  });

  it('detects TypeScript and npm', () => {
    const tech = readJson(path.join(knowledgeDir, 'technologies.json')) as {
      languages: string[];
      packageManagers: string[];
    };
    assert.ok(tech.languages.includes('TypeScript'), 'TypeScript not detected');
    assert.ok(tech.packageManagers.length > 0, 'package manager not detected');
  });

  it('validation passes (output contains Status: passed)', () => {
    const result = runCli([FIXTURE_TS]);
    assert.ok(/Status: passed/.test(result.stdout), 'Validation did not pass');
  });

  it('source files are unchanged after the run', () => {
    const before = collectSourceFiles(FIXTURE_TS);

    // Run a second time
    runCli([FIXTURE_TS]);

    for (const [rel, content] of before) {
      const current = fs.readFileSync(path.join(FIXTURE_TS, rel), 'utf-8');
      assert.equal(current, content, `Source file modified: ${rel}`);
    }
  });

  it('no output is written outside the fixture directory', () => {
    // Snapshot which directories exist in sibling fixtures before an isolated run,
    // then run again and confirm nothing new appeared outside the target.
    const tempFixture = fs.mkdtempSync(path.join(require('node:os').tmpdir(), 'isolation-check-'));
    fs.writeFileSync(path.join(tempFixture, 'package.json'), JSON.stringify({ name: 'isolation', version: '1.0.0' }));
    fs.mkdirSync(path.join(tempFixture, 'src'), { recursive: true });
    fs.writeFileSync(path.join(tempFixture, 'src', 'index.ts'), 'export const x = 1;\n');

    const siblingBefore = fs.readdirSync(FIXTURES_DIR);

    try {
      const result = runCli([tempFixture]);
      assert.equal(result.status, 0, `Isolation run failed: ${result.stdout}`);

      // The sibling fixture listing must not have grown
      const siblingAfter = fs.readdirSync(FIXTURES_DIR);
      assert.deepEqual(siblingBefore, siblingAfter, 'CLI created files in the fixtures directory');

      // Only the temp fixture's .ai-docs should have been created
      assert.ok(fs.existsSync(path.join(tempFixture, '.ai-docs')), 'CLI did not create .ai-docs in target');
    } finally {
      fs.rmSync(tempFixture, { recursive: true, force: true });
    }
  });
});

describe('Release integration — Fixture A incremental second run', () => {
  it('detects incremental mode and skips unchanged documents', () => {
    // First run must already have happened in the previous describe block.
    const result = runCli([FIXTURE_TS]);
    assert.equal(result.status, 0, `Second run failed:\n${result.stdout}`);

    assert.ok(
      /Initial run: no/.test(result.stdout) || /Skipped unchanged:/.test(result.stdout),
      'Incremental mode not detected on second run',
    );
  });

  it('generated docs remain stable across identical runs (excluding volatile files)', () => {
    // ai-readiness.md is always regenerated by the readiness step and carries the
    // current-run timestamp — it is intentionally volatile. All other generated
    // docs are skipped unchanged on an incremental run with no PKM changes.
    const VOLATILE_DOCS = new Set(['ai-readiness.md']);

    const readAll = (): Map<string, string> => {
      const docsDir = path.join(FIXTURE_TS, '.ai-docs');
      const result = new Map<string, string>();
      for (const name of fs.readdirSync(docsDir)) {
        if (name.endsWith('.md') && !VOLATILE_DOCS.has(name)) {
          result.set(name, fs.readFileSync(path.join(docsDir, name), 'utf-8'));
        }
      }
      return result;
    };

    runCli([FIXTURE_TS]);
    const before = readAll();
    runCli([FIXTURE_TS]);
    const after = readAll();

    for (const [name, content] of before) {
      assert.equal(after.get(name), content, `Generated doc changed on identical run: ${name}`);
    }
  });

  it('preserves user-created files without the generated marker', () => {
    const docsDir = path.join(FIXTURE_TS, '.ai-docs');
    const userFile = path.join(docsDir, 'my-notes.md');
    const content = '# My Notes\n\nUser-written content.\n';

    fs.writeFileSync(userFile, content, 'utf-8');
    runCli([FIXTURE_TS]);

    assert.ok(fs.existsSync(userFile), 'User file was deleted');
    assert.equal(fs.readFileSync(userFile, 'utf-8'), content, 'User file was modified');

    fs.unlinkSync(userFile);
  });
});

describe('Release integration — Staged documentation workflow (Fixture A)', () => {
  const docsDir = path.join(FIXTURE_TS, '.ai-docs');
  const knowledgeDir = path.join(docsDir, 'knowledge');

  const PLAYBOOK_PATHS = [
    'AI_START_HERE.md',
    'CONTEXT_ROUTER.md',
    'DOCUMENTATION_MAINTENANCE.md',
    'DOCUMENTATION_STATUS.md',
    'PROJECT_MAP.md',
    'code/index.md',
    'module-documentation-plan.md',
  ] as const;

  before(() => {
    // Reuse Fixture A outputs from the earlier first-run block when present;
    // otherwise create a clean baseline for staged assertions.
    if (!fs.existsSync(path.join(knowledgeDir, 'project-knowledge.json'))) {
      removeDocsDir(FIXTURE_TS);
      const result = runCli([FIXTURE_TS]);
      assert.equal(result.status, 0, `Staged baseline run failed:\n${result.stdout}\n${result.stderr}`);
    }
  });

  it('persists stagedDocumentation.modulePlan after module discovery', () => {
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: {
        modules?: Array<{ relativePath: string; name: string; type?: string }>;
        stagedDocumentation?: {
          modulePlan?: {
            status: string;
            entries: Array<{ moduleId: string; documentPath: string; order: number }>;
          };
        };
      };
    };

    const modules = pkm.analysis.modules ?? [];
    assert.ok(modules.length > 0, 'Expected discovered modules for staged planning');

    // Documentation-only modules are excluded from the module plan (they don't need AI cards)
    const productModules = modules.filter((m) => m.type !== 'documentation');

    const modulePlan = pkm.analysis.stagedDocumentation?.modulePlan;
    assert.ok(modulePlan, 'stagedDocumentation.modulePlan missing from PKM');
    assert.equal(modulePlan.entries.length, productModules.length);

    const moduleIds = new Set(modules.map((module) => module.relativePath));
    for (const entry of modulePlan.entries) {
      assert.ok(moduleIds.has(entry.moduleId), `Unexpected module-plan entry: ${entry.moduleId}`);
      assert.ok(entry.documentPath.startsWith('code/components/'));
      assert.ok(entry.order >= 1);
    }
  });

  it('writes playbook routing docs and the module-plan document', () => {
    for (const relativePath of PLAYBOOK_PATHS) {
      const absolutePath = path.join(docsDir, relativePath);
      assert.ok(fs.existsSync(absolutePath), `${relativePath} missing`);
      const content = fs.readFileSync(absolutePath, 'utf-8');
      assert.ok(content.startsWith(GENERATED_MARKER), `${relativePath} missing generated marker`);
    }
  });

  it('writes one module document per discovered module from PKM plan entries', () => {
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: {
        modules?: Array<{ relativePath: string; name: string; responsibility: string }>;
        stagedDocumentation?: {
          modulePlan?: {
            entries: Array<{ moduleId: string; documentPath: string; moduleName: string }>;
          };
        };
      };
    };

    const entries = pkm.analysis.stagedDocumentation?.modulePlan?.entries ?? [];
    assert.ok(entries.length > 0, 'Expected module-plan entries');

    for (const entry of entries) {
      const absolutePath = path.join(docsDir, entry.documentPath);
      assert.ok(fs.existsSync(absolutePath), `Module doc missing: ${entry.documentPath}`);

      const content = fs.readFileSync(absolutePath, 'utf-8');
      assert.ok(content.startsWith(GENERATED_MARKER), `${entry.documentPath} missing marker`);
      assert.ok(
        content.includes('## Deterministic module facts'),
        `${entry.documentPath} should render deterministic PKM facts`,
      );
      assert.ok(
        content.includes(entry.moduleId) || content.includes(entry.moduleName),
        `${entry.documentPath} should reference the module from PKM`,
      );
    }
  });

  it('renders module-plan Markdown from PKM entries rather than empty placeholders', () => {
    const planPath = path.join(docsDir, 'module-documentation-plan.md');
    const content = fs.readFileSync(planPath, 'utf-8');
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: {
        stagedDocumentation?: {
          modulePlan?: { entries: Array<{ moduleId: string }> };
        };
      };
    };
    const firstModuleId =
      pkm.analysis.stagedDocumentation?.modulePlan?.entries[0]?.moduleId ?? '';

    assert.ok(content.includes('module-documentation-plan') || /module/i.test(content));
    assert.ok(firstModuleId.length > 0);
    assert.ok(
      content.includes(firstModuleId),
      'module-documentation-plan.md should list PKM module-plan entries',
    );
  });

  it('persists staged-documentation.json split file when staged state exists', () => {
    const stagedPath = path.join(knowledgeDir, 'staged-documentation.json');
    assert.ok(fs.existsSync(stagedPath), 'staged-documentation.json missing');

    const staged = readJson(stagedPath) as {
      stagedDocumentation?: {
        modulePlan?: { entries: unknown[] };
        execution?: Array<{ stageId: string }>;
      };
    };
    assert.ok(staged.stagedDocumentation?.modulePlan);
    assert.ok(
      staged.stagedDocumentation?.execution?.some((entry) => entry.stageId === 'module-plan'),
    );
  });

  it('skips AI architecture and module fan-out without --ai (deterministic staged plan still runs)', () => {
    const result = runCli([FIXTURE_TS]);
    assert.equal(result.status, 0, result.stdout);

    assert.ok(
      /Generate Architecture Context/.test(result.stdout),
      'Expected architecture stage in pipeline checklist',
    );
    assert.ok(
      /Generate Module Documentation Plan/.test(result.stdout),
      'Expected module-plan stage in pipeline checklist',
    );
    assert.ok(
      /Generate Module Documentation/.test(result.stdout),
      'Expected module documentation stage in pipeline checklist',
    );

    // Without --ai these AI stages are skipped by design; residual AI coverage
    // lives in src/ai/*.test.ts with fake providers.
    assert.doesNotMatch(result.stdout, /AI Analysis:/);
  });
});

describe('Release integration — Fixture B (Monorepo)', () => {
  const docsDir = path.join(FIXTURE_MONO, '.ai-docs');
  const knowledgeDir = path.join(docsDir, 'knowledge');

  before(() => {
    removeDocsDir(FIXTURE_MONO);
  });

  it('exits with code 0', () => {
    const result = runCli([FIXTURE_MONO]);
    assert.equal(result.status, 0, `CLI failed:\n${result.stdout}\n${result.stderr}`);
  });

  it('discovers multiple modules', () => {
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: { modules?: Array<{ name: string }> };
    };
    const moduleCount = pkm.analysis.modules?.length ?? 0;
    assert.ok(moduleCount >= 2, `Expected at least 2 modules, got ${moduleCount}`);
  });

  it('emits one module card per discovered module from staged modulePlan', () => {
    const pkm = readJson(path.join(knowledgeDir, 'project-knowledge.json')) as {
      analysis: {
        modules?: Array<{ relativePath: string; type?: string }>;
        stagedDocumentation?: {
          modulePlan?: { entries: Array<{ documentPath: string }> };
        };
      };
    };

    const modules = pkm.analysis.modules ?? [];
    const productModules = modules.filter((m) => m.type !== 'documentation');
    const entries = pkm.analysis.stagedDocumentation?.modulePlan?.entries ?? [];
    assert.ok(modules.length >= 2, `Expected >=2 modules, got ${modules.length}`);
    assert.equal(entries.length, productModules.length);

    for (const entry of entries) {
      assert.ok(
        fs.existsSync(path.join(docsDir, entry.documentPath)),
        `Missing module card: ${entry.documentPath}`,
      );
    }
  });

  it('generates dependency-map.md', () => {
    assert.ok(fs.existsSync(path.join(docsDir, 'dependency-map.md')), 'dependency-map.md missing');
  });

  it('ai-readiness.json exists and is valid', () => {
    const json = readJson(path.join(knowledgeDir, 'ai-readiness.json')) as {
      aiReadiness: { overallScore: number };
    };
    const score = json.aiReadiness.overallScore;
    assert.ok(score >= 0 && score <= 100, `Score out of range: ${score}`);
  });

  it('validation passes', () => {
    const result = runCli([FIXTURE_MONO]);
    assert.ok(/Status: passed/.test(result.stdout), 'Validation did not pass for monorepo fixture');
  });
});

describe('Release integration — Fixture C (Minimal)', () => {
  const docsDir = path.join(FIXTURE_MINIMAL, '.ai-docs');
  const knowledgeDir = path.join(docsDir, 'knowledge');

  before(() => {
    removeDocsDir(FIXTURE_MINIMAL);
  });

  it('exits with code 0 on minimal unknown-stack project', () => {
    const result = runCli([FIXTURE_MINIMAL]);
    assert.equal(result.status, 0, `CLI failed on minimal:\n${result.stdout}\n${result.stderr}`);
  });

  it('creates project-knowledge.json', () => {
    assert.ok(fs.existsSync(path.join(knowledgeDir, 'project-knowledge.json')));
  });

  it('score is in valid range (not unfairly penalized)', () => {
    const json = readJson(path.join(knowledgeDir, 'ai-readiness.json')) as {
      aiReadiness: { overallScore: number };
    };
    assert.ok(json.aiReadiness.overallScore >= 0 && json.aiReadiness.overallScore <= 100);
  });

  it('generates a technology-overview.md fallback for unknown stack', () => {
    assert.ok(fs.existsSync(path.join(docsDir, 'technology-overview.md')), 'technology-overview.md missing for unknown stack');
  });

  it('validation passes with no crashes', () => {
    const result = runCli([FIXTURE_MINIMAL]);
    assert.ok(/Status: passed/.test(result.stdout), 'Validation did not pass for minimal fixture');
  });
});

describe('Release integration — Security: path traversal', () => {
  it('rejects --docs-dir with .. path separator', () => {
    const result = runCli([FIXTURE_TS, '--docs-dir', '../escape']);
    assert.equal(result.status, 1, 'Expected exit 1 for path traversal docs-dir');
  });

  it('rejects absolute --docs-dir', () => {
    const result = runCli([FIXTURE_TS, '--docs-dir', '/tmp/evil']);
    assert.equal(result.status, 1, 'Expected exit 1 for absolute docs-dir');
  });

  it('does not write outside the target repository on a normal run', () => {
    removeDocsDir(FIXTURE_TS);
    runCli([FIXTURE_TS]);

    // Verify no unexpected directories were created in the project root
    const leaked = path.join(PROJECT_ROOT, 'fixture-typescript-leak');
    assert.ok(!fs.existsSync(leaked), 'CLI leaked files outside target repository');
  });
});

describe('Release integration — CLI contract', () => {
  it('--help exits with 0 when used alone', () => {
    const result = runCli(['--help']);
    assert.equal(result.status, 0, '--help should exit 0');
    assert.ok(result.stdout.includes('ai-project-docs'), '--help output missing tool name');
  });

  it('no arguments exits with 1', () => {
    assert.equal(runCli([]).status, 1);
  });

  it('nonexistent path exits with 1 and reports "does not exist"', () => {
    const result = runCli(['/nonexistent/path/fixture-xyz-' + Date.now()]);
    assert.equal(result.status, 1);
    assert.ok(
      /does not exist/i.test(result.stdout + result.stderr),
      'Expected "does not exist" message',
    );
  });

  it('file target instead of directory exits with 1', () => {
    const tmpFile = path.join(require('node:os').tmpdir(), `release-test-file-${Date.now()}.txt`);
    fs.writeFileSync(tmpFile, 'not a directory');
    try {
      const result = runCli([tmpFile]);
      assert.equal(result.status, 1);
      assert.ok(
        /not a directory/i.test(result.stdout + result.stderr),
        'Expected "not a directory" message',
      );
    } finally {
      fs.rmSync(tmpFile, { force: true });
    }
  });

  it('unknown flag exits with 1', () => {
    assert.equal(runCli([FIXTURE_TS, '--unknown-flag-xyz']).status, 1);
  });

  it('unsupported --ai-provider exits with 1', () => {
    const result = runCli([FIXTURE_TS, '--ai-provider', 'nonexistent-provider']);
    assert.equal(result.status, 1, 'Expected exit 1 for unsupported provider');
  });

  it('--target without --export-agents exits with 1', () => {
    const result = runCli([FIXTURE_TS, '--target', 'cursor']);
    assert.equal(result.status, 1, 'Expected exit 1 for --target without --export-agents');
  });

  it('blocked docs directory exits with 3', () => {
    const blockFile = path.join(FIXTURE_TS, '.ai-docs-blocked-test');
    fs.writeFileSync(blockFile, 'blocks directory');
    try {
      const result = runCli([FIXTURE_TS, '--docs-dir', '.ai-docs-blocked-test']);
      assert.equal(result.status, 3, 'Expected exit 3 for blocked docs directory');
    } finally {
      fs.rmSync(blockFile, { force: true });
    }
  });
});
