export {
  GENERATOR_VERSION,
  PROJECT_KNOWLEDGE_SCHEMA_VERSION,
} from './constants';
export {
  type AgentExportFileKnowledge,
  type AgentExportResultKnowledge,
  type AgentExportsKnowledge,
  type AgentExportTarget,
  type AiInsightsKnowledge,
  type AnalysisKnowledge,
  type AnalysisKnowledgeStatus,
  type ArchitectureStageKnowledge,
  type ChangeBaselineStatus,
  type ChangeSection,
  type ChangeSummaryKnowledge,
  type DependencyEdgeChangeKnowledge,
  type DocumentImpactKnowledge,
  type DocumentImpactSummaryKnowledge,
  type ConventionCategory,
  type ConventionConfidence,
  type ConventionEvidence,
  type ConventionEvidenceType,
  type ConventionKnowledge,
  type DocumentationKnowledge,
  type NavigationEntry,
  type NavigationEntryConfidence,
  type NavigationKnowledgeSection,
  type NavigationMapKnowledge,
  type NavigationTaskType,
  type FolderClassification,
  type FolderKnowledge,
  type FolderKnowledgeConfidence,
  type ModuleDocumentationPlanEntry,
  type ModuleDocumentationPlanKnowledge,
  type ModuleDocumentationResultKnowledge,
  type ModuleDocumentationResultsKnowledge,
  type ModuleKnowledge,
  type ModuleKnowledgeConfidence,
  type ModuleType,
  type OperationalContextConfidence,
  type OperationalContextKnowledge,
  type OperationalEnvVar,
  type OperationalRunCommand,
  type DependencyGraphKnowledge,
  type DependencyNode,
  type DependencyEdge,
  type DependencyEdgeType,
  type DependencyEdgeConfidence,
  type DependencyEdgeEvidence,
  type KnowledgeMetadata,
  type ProjectKnowledge,
  type RepositoryKnowledge,
  type CapabilityMapItem,
  type CapabilityMapStageKnowledge,
  type RouterStageEntry,
  type RouterStageKnowledge,
  type StagedDocumentationKnowledge,
  type StagedDocumentationStageExecution,
  type StagedDocumentationStageId,
  type StagedDocumentationStatus,
  type TechnologyKnowledge,
} from './project-knowledge';
export {
  getDocsDir,
  getDocsRootPath,
  getDocumentationPlan,
  getProjectRoot,
  hasPartialAnalysis,
  isAnalysisComplete,
} from './accessors';
export {
  formatKnowledgeRelativeFilePath,
  getKnowledgeDirectoryRelativePath,
  KNOWLEDGE_DIRECTORY_NAME,
  KNOWLEDGE_FILE_NAMES,
  listKnowledgeRelativeFilePaths,
  listPersistedKnowledgeRelativeFilePaths,
  resolveKnowledgeDirectory,
  resolveKnowledgeFilePath,
  type KnowledgeFileName,
} from './knowledge-paths';
export {
  persistAiReadinessKnowledge,
  persistProjectKnowledge,
  type KnowledgePersistenceResult,
} from './knowledge-writer';
export {
  buildProjectKnowledge,
  createPendingAnalysisKnowledge,
  mapDocumentationKnowledge,
  mapRepositoryKnowledge,
  mapTechnologyKnowledge,
  type KnowledgeBuilderInput,
} from './knowledge-builder';
